# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyCampus' do


pod 'JPush'

# 集成微信(精简版0.2M)
pod ‘UMengUShare/Social/ReducedWeChat'

# 集成QQ/QZone/TIM(精简版0.5M)
pod ‘UMengUShare/Social/ReducedQQ'

# 集成新浪微博(精简版1M)
pod ‘UMengUShare/Social/ReducedSina'

pod 'TZImagePickerController'

end